version: "3.0"
services:
  db:
    container_name: "db"
    image: "postgres:14.1-alpine"
    restart: always
    environment:
        - POSTGRES_USER=${POSTGRES_USER:-app_user}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change_me}
        - POSTGRES_DB=${POSTGRES_DB:-app_db}
    ports:
        - "5432:5432"
    networks:
        - custom

  FastApi_education_platform_app:
    container_name: "FastApi_education_platform_app"
    image: "fastapi_education_platform_app"
    environment:
      REAL_DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER:-app_user}:${POSTGRES_PASSWORD:-change_me}@db:5432/${POSTGRES_DB:-app_db}"
      ACCESS_TOKEN_EXPIRE_MINUTES: "${ACCESS_TOKEN_EXPIRE_MINUTES:-30}"
      SECRET_KEY: "${SECRET_KEY:-demo-secret-change-me}"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8000:8000"
    networks:
      - custom
networks:
    custom:
        driver: bridge
